###

Content-Type: application/json



###
http://localhost:3000


/////////////////////////
// Workouts

###
//http://localhost:3000/api/v1/workouts

###
//POST http://localhost:3000/api/v1/workouts/seed


/////////////////////////
// Users

###
//http://localhost:3000/api/v1/products

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "firstName": "Josh",
  "lastName": "Chaffy",
  "email": "joshchaffy@gmail.com",
  "password": "joshchaffy"
}

###
PATCH http://localhost:3000/api/v1/users/4
Content-Type: application/json

{
  "firstName": "Josh Chaffy"
}

###
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json

{
  "firstName": "Josh",
  "lastName": "Chaffy",
  "email": "joshchaffy@gmail.com",
  "password": "joshchaffy"
}

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "email": "joshchaffy@gmail.com",
  "password": "joshchaffy"
}